[phases.setup]
nixPkgs = [
    "python311",
    "libxcb",
    "xorg.libX11",
    "libGL",
    "glib",
    "zlib"
]

[phases.build]
cmds = ["python -m venv .venv", ". .venv/bin/activate && pip install -r requirements.txt"]

[start]
cmd = "uvicorn main:app --host 0.0.0.0 --port $PORT"
